### ISSUE TITLE
Cast column_default to string

### ISSUE THREAD

**Issue by olavloite** [googleapis/dotnet-spanner-entity-framework#141]
Any query that references the `information_schema.columns.column_default` column should cast the value to string: https://github.com/googleapis/dotnet-spanner-entity-framework/blob/ce757fbd89dfa9f91d7be48d1a8a43500a20d27f/Google.Cloud.EntityFrameworkCore.Spanner/Scaffolding/Internal/SpannerDatabaseModelFactory.cs#L113

cc @dttran

**Comment by dttran** [comment]
We'd need to prioritize this change. This is blocking a Spanner feature from being released.
