### ISSUE TITLE
Publish EntityFramework.Core 3.0 release on NuGet.

### ISSUE THREAD

**Issue by abbottdev** [googleapis/dotnet-spanner-entity-framework#460]
The 3.0 release was created 2 weeks ago but it's not currently published on NuGet. 

Can we publish the release here: https://github.com/googleapis/dotnet-spanner-entity-framework/releases/tag/Google.Cloud.EntityFrameworkCore.Spanner-3.0.0 to NuGet?

**Comment by amanda-tarafa** [comment]
We have no ETA at the moment, but we are actively working on it.

**Comment by amanda-tarafa** [comment]
I'm closing this as duplicate of https://github.com/googleapis/dotnet-spanner-entity-framework/issues/459
