### ISSUE TITLE
v3.0 - Value Converters aren't respected

### ISSUE THREAD

**Issue by abbottdev** [googleapis/dotnet-spanner-entity-framework#462]
When using `ValueConversion` in Entity Framework you're able to (according to the docs) retype your Model types before database conversion - for example, I could flatten a complex type, into a single string property - and EF should map using that remapped property.

However, it looks as though the type mapping used in Spanner doesn't support this - I'm noticing this behaviour specifically trying to remap a `HashSet` to a `List` so that the standard cloud spanner mappings to `Array<string` etc. take precedence. But if I use `entity.Property(x => x.Prop).HasConversion` - nothing is changed.

I have a branch of a fork where the tests fail - (there are some other test failures but I'm unsure whether that's a me issue or not - but the Scaffolding tests are showing the problem.): https://github.com/abbottdev/dotnet-spanner-entity-framework/tree/feature/hashset-tests

Or you can see the diff here:
https://github.com/googleapis/dotnet-spanner-entity-framework/compare/main...abbottdev:dotnet-spanner-entity-framework:feature/hashset-tests?expand=1

#### Environment details

  - Programming language:C#
  - OS: MacOS
  - Language runtime version: Net8.0
  - Package version: v3.0.0 (preview)

#### Steps to reproduce

  1. Add a HashSet<string> property to a EF mapped class: 
  ```
      public partial class Album
    {
        public long SingerId { get; set; }
        public long AlbumId { get; set; }
        public string Title { get; set; }
        public virtual Singer Singer { get; set; }
        public HashSet<string> Awards { get; set; } = new HashSet<string>(); // new prop
    }
  ```
  2. Add an Array type mapping to the SQL databases:
  ```
  CREATE TABLE Albums (
  AlbumId     INT64 NOT NULL,
  Title       STRING(100) NOT NULL,
  ReleaseDate DATE,
  SingerId    INT64 NOT NULL,
  Awards    ARRAY<STRING(256)> NOT NULL, -- this line
  CONSTRAINT FK_Albums_Singers FOREIGN KEY (SingerId) REFERENCES Singers (SingerId),
) PRIMARY KEY (AlbumId);
  ```
  2. Add the property to the DbContext with a `Conversion` function like so:
  ```
                entity.Property(a => a.Awards)
                    .HasConversion(
                        hashset => hashset.ToList(),
                        list => list.ToHashSet()
                    );
  ```
   3. Try and run the tests using an emulator, and you receive exception ``No coercion operator is defined between types 'System.Collections.Generic.HashSet`1[System.String]' and 'System.Collections.Generic.List`1[System.String]'.``
   
   Example failing test:
   ```
     Failed Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.QueryTests.CanUseOuterJoin [1 ms]
  Error Message:
   System.InvalidOperationException : No coercion operator is defined between types 'System.Collections.Generic.HashSet`1[System.String]' and 'System.Collections.Generic.List`1[System.String]'.
  Stack Trace:
   ```

Thanks!

**Comment by jhaEShauliuk** [comment]
has the same issue when we converting enum to database Int value. Custom Conversion logic do not help. Keep getting an error "ArgumentException: Argument types do not match"

```
modelBuilder.Entity<TableName>()
                .Property(c => c.EnumType)
                .HasConversion<int>();
```

**Comment by abbottdev** [comment]
I struggled a bit with the docs @jhaEShauliuk - I found that a combination of EF 3.0, I think there's some type mappings missing somewhere. For example, for the Enum part I was able to get this working by doing the following:
```
modelBuilder.Entity<TableName>()
                .Property(c => c.EnumType)
                .HasConversion(new EnumToNumberConverter<EnumType, long>());
```
The key part was that if I used int instead of long it would fail. (Hope that helps you out along the way.)
